### PR TITLE
added initial .travis.yml

### PR DESCRIPTION
**Pull request by krichter722**

### CODE REVIEW

**Comment by pwithnall** [comment]
Why do you want to merge this into libgdata? Are you planning on maintaining a CI system for it?

**Comment by krichter722** [comment]
It's an easy test of the build process based on default build commands and helps people working with Github and Travis. I don't think that it needs any maintenance.

**Comment by pwithnall** [comment]
> It's an easy test of the build process based on default build commands and helps people working with Github and Travis. I don't think that it needs any maintenance.

Who’s working with github and Travis for libgdata? I’d be interested to know.

GNOME has its own CI system ([Continuous](https://wiki.gnome.org/Projects/GnomeContinuous)) which I use instead of Travis. I’m not against adding a `.travis.yml`, but I am not going to maintain it; you’d need to do that yourself.

**Comment by pwithnall** [comment]
I tweaked the commit message and applied it to git master:

```
commit 9925d4bba8e58d3cfa85ad6216484eaa2cc72de5
Author: Karl-Philipp Richter <krichter722@aol.de>
Date:   Fri Jun 30 20:35:19 2017 +0200

    build: Add initial .travis.yml
    
    Reviewed-by: Philip Withnall <withnall@endlessm.com>
    
    https://github.com/GNOME/libgdata/pull/1

 .travis.yml | 12 ++++++++++++
 1 file changed, 12 insertions(+)
```

**Pull request closed without merging**
